Repository kaamiki/kaamiki, pull requests merged in 2020-10, with the labels that each got.

#1 Upstream code of conduct assets to git
  elements/img/code-of-conduct-banner.png
  elements/psd/code-of-conduct-banner.psd
Labels: documentation

#2 Add kaamiki setup and update README.md
  CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT_HN.md
  README.md
  __init__.py
  kaamiki/__init__.py
  requirements.txt
  setup.py
Labels: documentation

#6 Minor typo changes
  CODE_OF_CONDUCT_HN.md
Labels: documentation

#7 Add support for thread-safe singleton class
  kaamiki/__init__.py
Labels: enhancement

#8 Add logging module and merge critical changes
  kaamiki/__init__.py
  kaamiki/utils/__init__.py
  kaamiki/utils/logging.py
Labels: enhancement, help wanted

#9 Add support for multiple FileHandlers
  kaamiki/utils/logging.py
Labels: enhancement, help wanted

#13 Add parser module
  kaamiki/parser.py
Labels: enhancement

#15 Update example in Logger class
  kaamiki/__init__.py
  kaamiki/utils/logger.py
Labels: enhancement
